print("What do you get when you cross a snowman with a vampire?")
input()
print("Frostbite!")
print()
print("what do dentists call a astronaut\'s cavity?")
input()
print("A black hole!")
print()
print("Knock knock.")
input()
print("Who\'s there?")
print()
print("Interrupting cow.")
input()
print("Interrupting cow wh", end = ' ')
print("-Moo!")