# Generated by Django 2.1.5 on 2019-04-23 02:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followings',
            field=models.ManyToManyField(blank=True, related_name='user_follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
