# Generated by Django 2.1.5 on 2019-02-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='urlplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('shorturl', models.TextField()),
                ('custom', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
