# Generated by Django 2.1.8 on 2019-05-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('audi', models.IntegerField()),
                ('score', models.IntegerField()),
                ('summary', models.CharField(max_length=200)),
                ('poster_url', models.CharField(max_length=300)),
                ('preview_url', models.CharField(max_length=300)),
            ],
        ),
    ]
