# Generated by Django 2.1.8 on 2019-05-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('audi', models.IntegerField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('summary', models.CharField(blank=True, max_length=200, null=True)),
                ('poster_url', models.CharField(blank=True, max_length=300, null=True)),
                ('preview_url', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
